# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echobot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiGramRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TriGramRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeightedPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('personality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echobot.Personality')),
            ],
        ),
        migrations.RemoveField(
            model_name='phraserelation',
            name='post',
        ),
        migrations.RemoveField(
            model_name='phraserelation',
            name='prev',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='personality',
        ),
        migrations.DeleteModel(
            name='PhraseRelation',
        ),
        migrations.AddField(
            model_name='trigramrelation',
            name='first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_phrase_in_trigram', to='echobot.Phrase'),
        ),
        migrations.AddField(
            model_name='trigramrelation',
            name='last',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_phrase_in_trigram', to='echobot.Phrase'),
        ),
        migrations.AddField(
            model_name='trigramrelation',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mid_phrase_in_trigram', to='echobot.Phrase'),
        ),
        migrations.AddField(
            model_name='bigramrelation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_phrase_in_bigram', to='echobot.Phrase'),
        ),
        migrations.AddField(
            model_name='bigramrelation',
            name='prev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_phrase_in_bigram', to='echobot.Phrase'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='weighted_personality_list',
            field=models.ManyToManyField(to='echobot.WeightedPersonality'),
        ),
    ]
